spring:
  application:
    name: reminder
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: utf-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: true
            required: true
      test-connection: false

# 邮箱
mail:
  enable: true
  username:
  password:
  to:
  subject: 买票
  text: 买票
