spring:
  application:
    name: reminder
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: utf-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: true
            required: true
      test-connection: false

# 邮箱
mail:
  enable: true
  username:
  password:
  to:
  subject: 买票
  text: 买票

# 掘金配置
juejin:
  cookie:

# 每日任务是否启用配置;
# key为 DailyTaskStrategyConstant 的常量
# value为 1或true则表示启用，其他值或未配置表示不启用
# daily_task_buy_ticket: 0

