name: Remind buy ticket
on:
  schedule:
    - cron: '0/3 * * * *'
  push:
    branches:
      - buy-ticket
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
      with:
          ref: buy-ticket
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run
      env:
        MAIL_USERNAME: zhongzx8080@qq.com
        MAIL_PASSWORD: ${{ secret.MAIL_PASSWORD }}
        MAIL_TO_0: zhongzx8080@qq.com
      run: |
        echo ls
        jar -jar target/reminder-0.0.1-SNAPSHOT.jar
