name: Remind buy ticket
on:
  schedule:
    - cron: '0/1 * * * *'
  push:
    branches:
      - buy-ticket
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run
      env:
        MAIL_USERNAME: zhongzx8080@qq.com
        MAIL_PASSWORD: ${{ secret.MAIL_PASSWORD }}
        MAIL_TO[0]: zhongzx8080@qq.com
      run: echo $MAIL_USERNAME
