# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jue jin checkin & draw by curl

on:
  schedule:
    - cron: '8 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkin
        run:  curl --location --request POST 'https://api.juejin.cn/growth_api/v1/check_in' --header 'cookie:${{ secrets.JUEJIN_COOKIE }}'
      - name: Draw
        run:  curl --location --request POST 'https://api.juejin.cn/growth_api/v1/lottery/draw' --header 'cookie:${{ secrets.JUEJIN_COOKIE }}'